JSON parse methods
pskramtai/PSI pull request #6
Opened 2020-09-30 17:34 UTC by pskramtai

2020-09-30 21:41 UTC, pskramtai commented on Comparison Engine/Comparison Engine/bin/Debug/netcoreapp3.1/barInput.json
> +        ]
Not sure if drink names are necessary in availableDrinks list but I decided to keep them for now.

2020-10-01 07:58 UTC, Raeppa commented
Looks good to me
Will probably need a way to write to file though in order to save the data to file

2020-10-01 17:52 UTC, ElektrosStulpas requested changes
The only critical thing that would be nice if you could look at before merging is the thing about List<Drink> in Data.cs. Other than that, the commit should not have Bar.cs and Drink.cs and I'm not sure why it's committing gitignore again

2020-10-01 17:52 UTC, ElektrosStulpas commented on Comparison Engine/Comparison Engine/Data/Data.cs
> +        }
Ar šitam metode neturėtų būti List<Drink>? Also might need to add some form of validation or catch exceptions in the future for reading from file

2020-10-01 17:52 UTC, ElektrosStulpas commented on Comparison Engine/Comparison Engine/Comparison Engine.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
Are we using both of these packages? Nes lygtais minėjai, kad nesigavo su Entities, tai if there's no features using them, they shouldn't be committed just yet. In that case would need to uninstall the package at the time of commit (maybe there's some less ape method of doing this, but I don't know of it yet)

2020-10-02 09:18 UTC, ElektrosStulpas approved these changes

2020-10-02 09:18 UTC, merged